language: java
env:
  global:
  - TESTMODEL_URL=http://localhost:8080/intermine-demo
  - TESTMODEL_PATH=intermine-demo
sudo: true
jdk:
  - openjdk8
script:
  - ls /usr/local/lib/jvm/
  - which java
  - ls /usr/local/lib/
  - bash init-biotestmine.sh
  - bash init-testmine.sh
  - echo "successfully built"
