language: java
env:
  global:
  - TESTMODEL_URL=http://localhost:8080/intermine-demo
  - TESTMODEL_PATH=intermine-demo
sudo: true
jdk:
  - openjdk8
services:
  - postgresql
jobs:
  include:
    - script: bash init-testmine.sh
    - script: bash init-biotestmine.sh
