language: java
sudo: true
dist: trusty
jdk:
  - openjdk13
services:
  - postgresql
jobs:
  include:
    - script: bash init-biotestmine.sh
    - script: bash init-testmine.sh
    - script: BUILD_DATASET=true bash init-biotestmine.sh
